### ISSUE TITLE
Important information about updating AKS-HCI to v1.0.9.1043 (April 2022 Update)

### ISSUE THREAD

**Issue by baziwane** [Azure/aksArc#185]
We are investigating an intermittent issue caused by a bug in the April Update (AKS-HCI v1.0.9.10413). This bug causes the workload cluster control plane to undergo a rolling update immediately after completing the AKS-HCI (management cluster) update. We are working on root causing this and will have a fix available in an upcoming release.
 
**Steps to diagnose (please do all of the following) **
 
1. Run Command: `Get-AksHciCluster -name <insert workload cluster name>`
 
Look for: `ProvisioningState` not equal to `Deployed`
 
2. Run: `kubectl get kcp <insert workload cluster name>-control-plane --kubeconfig (get-kvaconfig).kubeconfig -o yaml`
 
Look for a status value “False” for any of the following condition types:
 
- ControlPlaneComponentsHealthy, 
- MachinesReady, 
- MachinesSpecUpToDate
 
Below is a sample output, some of the content is omitted for brevity and the status should be at the bottom of the output:
 
```
...
status:
  conditions:
...
  - lastTransitionTime: "2022-04-27T21:15:36Z"
    status: "True"
    type: MachinesReady
  - lastTransitionTime: "2022-04-27T21:17:09Z"
    status: "False"
    type: MachinesSpecUpToDate
...
```
**Recommendation**

If you observe the any of the scenarios described above after running Update-AksHci, **please contact our engineering team and do not try upgrading the workload clusters**.  

<3 AKS-HCI Team
