### ISSUE TITLE
[BUG] Parameter "createSubDir" for SMB CSI StorageClass is invalid

### ISSUE THREAD

**Issue by johnliu55-msft** [Azure/aksArc#278]
**Describe the bug**
The official document [Use Container Storage Interface (CSI) file drivers in AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/container-storage-interface-files#use-smb-drivers) specifies when creating the `StorageClass`, an optional parameter `createSubDir` can be provided to choose whether to create a sub dir for new volume.

![image](https://user-images.githubusercontent.com/107901166/205031170-c1a10298-ce5f-4c29-b4e6-dc4009f3e3fd.png)

But with this StorageClass manifest, the PVC using this StorageClass will fail to provision:
```
kubectl get events
2s          Normal    Provisioning            persistentvolumeclaim/pvc-akshci-smb-csi                    External provisioner is provisioning volume for claim "default/pvc-akshci-smb-csi"
2s          Warning   ProvisioningFailed      persistentvolumeclaim/pvc-akshci-smb-csi                    failed to provision volume with StorageClass "smb-csi": rpc error: code = InvalidArgument desc = invalid parameter createSubDir in storage class
```

If I remove the parameter `createSubDir` from the StorageClass manifest, the PVC will be created without any error or warning.

**To Reproduce**
1. Follow the official document to create the SMB CSI StorageClass
2. Create a PVC using the following YAML:
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
     name: pvc-akshci-csi
    spec:
     accessModes:
     - ReadWriteOnce
     resources:
      requests:
       storage: 10Gi
    ```
3. Use `kubectl get events` to see the event
4. The provisioning of the PVC failed with message: `failed to provision volume with StorageClass "smb-csi": rpc error: code = InvalidArgument desc = invalid parameter createSubDir in storage class`

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- OS: Azure Stack HCI
- AKS-HCI Version: 1.0.15.11104
- Kubernetes Version (i.e. 1.18.8)

**Additional context**

**Collect log files**
- From a PowerShell Admin window run **Get-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by plumbery** [comment]
Hi, the same issue on my Stack HCI. AKS Any updates on this?

**Comment by apluchik** [comment]
Hi, the createSubDir parameter is now deprecated and removed since the May version of AksHci. The documentation will be updated to reflect this.

If you are upgrading from an older version of AksHci and hit an issue due to createSubDir being used, please recreate the storageClass without the createSubDir parameter as stated in:
https://learn.microsoft.com/en-us/azure/aks/hybrid/known-issues-storage#storage-pod-crashes-and-the-logs-say-that-the--createsubdir--parameter-is-invalid

**Comment by plumbery** [comment]
Hi @apluchik i remove  `createSubDir: "false"  # optional: create a sub dir for new volume` line in parameters and pvc bounded.    Thanks for your support.

example;

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-csi
provisioner: smb.csi.akshci.com
parameters:
   source: \\smb-server\share
   csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
   csi.storage.k8s.io/node-stage-secret-namespace: "default"
reclaimPolicy: Retain  # only Retain is supported
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
```
